// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs_EIP5Jh-9y9k-Zc0wrBKoQdjs1shJs4',
    appId: '1:391722102347:web:0ea95afba42c8b005f67ce',
    messagingSenderId: '391722102347',
    projectId: 'dalel-92924',
    authDomain: 'dalel-92924.firebaseapp.com',
    storageBucket: 'dalel-92924.firebasestorage.app',
    measurementId: 'G-RW8EMHWKBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd0BiiskSgfeHiZmY9In0z0grEor1Z-4I',
    appId: '1:391722102347:android:a64e9515fd5b3fe55f67ce',
    messagingSenderId: '391722102347',
    projectId: 'dalel-92924',
    storageBucket: 'dalel-92924.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfkkYlYGdGEqnhGwaJrkl29HGQB9po5NA',
    appId: '1:391722102347:ios:51acf2bb2d46d90a5f67ce',
    messagingSenderId: '391722102347',
    projectId: 'dalel-92924',
    storageBucket: 'dalel-92924.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfkkYlYGdGEqnhGwaJrkl29HGQB9po5NA',
    appId: '1:391722102347:ios:51acf2bb2d46d90a5f67ce',
    messagingSenderId: '391722102347',
    projectId: 'dalel-92924',
    storageBucket: 'dalel-92924.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs_EIP5Jh-9y9k-Zc0wrBKoQdjs1shJs4',
    appId: '1:391722102347:web:c5f751833c4a53f85f67ce',
    messagingSenderId: '391722102347',
    projectId: 'dalel-92924',
    authDomain: 'dalel-92924.firebaseapp.com',
    storageBucket: 'dalel-92924.firebasestorage.app',
    measurementId: 'G-R7W2RPGD1Y',
  );
}
